name: Fast-Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Bobcat repository
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git build-essential clang pkg-config \
          libgtk-3-dev libnotify-dev openssl libfreetype6-dev \
          libx11-dev libxinerama-dev libxrender-dev libxft-dev \
          libxdmcp-dev libfontconfig1-dev libxcb1-dev libxext-dev \
          libgdk-pixbuf2.0-dev zlib1g-dev libharfbuzz-dev libpango1.0-dev \
          libatk1.0-dev libcairo2-dev libglib2.0-dev libpng-dev
    
    - name: Download and compile the latest stable U++
      run: make download
      
    - name: Build Bobcat
      run:  make build       
