name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Bobcat repository
      uses: actions/checkout@v3
      with:
        path: Bobcat

    - name: Install dependencies (macOS)
      run: brew update  

    - name: Checkout U++ repository
      uses: actions/checkout@v3
      with:
        repository: ultimatepp/ultimatepp
        path: upp-source

    - name: Configure and build U++
      working-directory: upp-source
      run: |
        ./configure
        make -f ./umkMakefile -j 4

    - name: Build Bobcat
      working-directory: Bobcat
      run: |
        ../upp-source/umk ./,../upp-source/uppsrc Bobcat CLANG.bm -brvh +GUI,SHARED build/Bobcat
