name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Bobcat repository
      uses: actions/checkout@v3
      with:
        path: Bobcat

    - name: Download U++ Windows release
      run: |
        Invoke-WebRequest -Uri "https://www.ultimatepp.org/downloads/upp-win-17490.7z" -OutFile "upp-win.7z"

    - name: Extract U++ release
      run: |
        7z x upp-win.7z -oupp-source

    # Since there is a problem with UppHub access of umk, we'll checkout the required components manually.
    
    - name: Checkout TerminalCtrl repository
      uses: actions/checkout@v3
      with:
        repository: ismail-yilmaz/Terminal
        path: upp-source/upp/UppHub/Terminal

    - name: Checkout StackCtrl repository
      uses: actions/checkout@v3
      with:
        repository: ismail-yilmaz/StackCtrl
        path: upp-source/upp/UppHub/StackCtrl

    - name: Checkout MessageCtrl repository
      uses: actions/checkout@v3
      with:
        repository: ismail-yilmaz/MessageCtrl
        path: upp-source/upp/UppHub/MessageCtrl

    - name: Checkout Turtle repository
      uses: actions/checkout@v3
      with:
        repository: mirek-fidler/Turtle
        path: upp-source/upp/UppHub/Turtle
    
    # On Windows, no build file is generated. We are generating it dynamically with a basic configuration

    - name: Create a CLANG.bm file
      working-directory: upp-source/upp
      env: 
        UPP_ROOT: "..\\upp-source\\upp\\"
      run: |
        $content = @'
        BUILDER = "CLANG";
        COMPILER = "";
        COMMON_OPTIONS = "";
        COMMON_CPP_OPTIONS = "--std=c++17";
        COMMON_C_OPTIONS = "";
        COMMON_LINK = "";
        COMMON_FLAGS = "";
        DEBUG_INFO = "2";
        DEBUG_BLITZ = "1";
        DEBUG_LINKMODE = "0";
        DEBUG_OPTIONS = "";
        DEBUG_FLAGS = "";
        DEBUG_LINK = "-Wl,--stack,20000000";
        RELEASE_BLITZ = "1";
        RELEASE_LINKMODE = "0";
        RELEASE_OPTIONS = "-O3 ";
        RELEASE_FLAGS = "";
        RELEASE_LINK = "-Wl,--stack,20000000";
        DEBUGGER = "gdb";
        ALLOW_PRECOMPILED_HEADERS = "1";
        DISABLE_BLITZ = "0";
        PATH = "C${{ env.UPP_ROOT }}/bin/clang/bin;C${{ env.UPP_ROOT }}/bin/clang/x86_64-w64-mingw32/bin;C${{ env.UPP_ROOT }}/bin/SDL2/lib/x64;C${{ env.UPP_ROOT }}/bin/pgsql/x64/bin;C${{ env.UPP_ROOT }}/bin/mysql/lib64";
        INCLUDE = "C${{ env.UPP_ROOT }}/bin/SDL2/include;C${{ env.UPP_ROOT }}/bin/pgsql/x64/include;C${{ env.UPP_ROOT }}/bin/mysql/include;C${{ env.UPP_ROOT }}/bin/llvm";
        LIB = "C${{ env.UPP_ROOT }}/bin/SDL2/lib/x64;C${{ env.UPP_ROOT }}/bin/pgsql/x64/lib;C${{ env.UPP_ROOT }}/bin/mysql/lib64;C${{ env.UPP_ROOT }}/bin/llvm";
        LINKMODE_LOCK = "0";
        '@

        $content | Out-File -FilePath CLANG.bm -Encoding utf8
  
    - name: Build Bobcat
      working-directory: Bobcat
      run: |
        ..\upp-source\upp\umk.exe .\,..\upp-source\upp\uppsrc Bobcat CLANG.bm -arb +GUI,WIN64,WIN10 bobcat

